lamdabotweb/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView
from lamdabotweb import settings

urlpatterns = [
    path('admin/login/', RedirectView.as_view(url=settings.LOGIN_URL, permanent=True, query_string=True)),
    path('admin/', admin.site.urls),
    path('discord_oauth2/', include('discord_oauth2.urls')),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'LambdaBot administration'

webapi/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from webapi import views

app_name = 'webapi'

schema_view = get_schema_view(title='LambdaBot API')

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'memeimagepool', views.MemeImagePoolViewSet)
router.register(r'memesourceimg', views.MemeSourceImageViewSet)
router.register(r'memetemplate', views.MemeTemplateViewSet)
router.register(r'meem', views.MeemViewSet)

urlpatterns = [
    path('schema/', schema_view),
    path('', include(router.urls)),
]

website/urls.py
from django.urls import path
from django.views.generic import RedirectView
from website import views, settings

app_name = 'website'

urlpatterns = [
    path('', views.homepage, name='home_view'),
    path('meme/<uuid:meme_id>/', views.meme_info_view, name='meme_view'),
    path('meme_info/<uuid:meme_id>/', views.meme_info_view, name='meme_info_view'),
    path('generate/', views.meme_preview, name='meme_preview'),
    path('generate/<str:template>/', views.meme_preview, name='meme_preview_template'),
    path('invite/', RedirectView.as_view(url=settings.BOT_INVITE_URL, permanent=True), name='bot_invite'),
    path('submit/', views.submit, name='submit'),
]

website/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.core.exceptions import ValidationError
from discordbot.models import DiscordUser
from memeviewer.models import MemeSourceImage, POOL_TYPE_SRCIMGS, POOL_TYPE_ALL
from website import settings


class MemeSourceImageForm(forms.ModelForm):
    class Meta:
        model = MemeSourceImage
        fields = ('friendly_name', 'image_pool', 'image_file', 'captcha')
        widgets = {
            'friendly_name': forms.TextInput(attrs={'placeholder': 'Image name'}),
        }

    def __init__(self, user: DiscordUser, *args, **kwargs):
        super(MemeSourceImageForm, self).__init__(*args, **kwargs)
        avail = user.available_pools.filter(pool_type__in=[POOL_TYPE_SRCIMGS, POOL_TYPE_ALL])
        self.fields['image_pool'] = forms.ModelChoiceField(avail.order_by('friendly_name'), empty_label=None)
        self.initial['image_pool'] = avail.get(name='halflife')

    def clean_image_file(self):
        image = self.cleaned_data['image_file']
        if image.size > settings.MEEM_MAX_SRCIMG_SIZE:
            raise ValidationError('Image is too big (should be smaller than %(size)s KB)', params={'size': settings.MEEM_MAX_SRCIMG_SIZE / 1000})
        return image

    captcha = ReCaptchaField()

website/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404, HttpResponse
from discordbot.models import DiscordMeem, DiscordServer, DiscordSourceImgSubmission
from memeviewer.models import Meem, MemeImagePool, MemeTemplate, MemeSourceImage
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from website.forms import MemeSourceImageForm


def homepage(request):
    return render(request, 'website/home.html', {
        'discord_meme_count': DiscordMeem.objects.count(),
        'sourceimg_count': MemeSourceImage.objects.filter(accepted=True).count(),
        'template_count': MemeTemplate.objects.filter(accepted=True).count(),
        'users_count': DiscordMeem.objects.values_list('discord_user__user_id', flat=True).distinct().count(),
        'servers_count': DiscordServer.objects.count(),
        'meme_count': Meem.objects.order_by('-gen_date').first().number,
    })


def meme_info_view(request, meme_id):
    """ displays meme info page """

    try:
        meme = Meem.objects.get(meme_id=meme_id)
        meme.make_img()
    except Meem.DoesNotExist:
        raise Http404("Invalid meme ID")

    return render(request, 'website/meme_info_view.html', {
        'meme': meme,
    })


@staff_member_required
def meme_preview(request, template=None):
    pools = MemeImagePool.objects.filter(name__in=request.GET.get('pools', '').split())
    try:
        template = template is not None and MemeTemplate.objects.get(name=template) or None
    except MemeTemplate.DoesNotExist:
        raise Http404("template does not exist")
    meme = Meem.generate(pools, 'default', saveme=False, template=template)
    response = HttpResponse(content_type='image/jpeg')
    meme.make_img(saveme=False).save(response, "JPEG")
    return response


@login_required
def submit(request):
    # todo: what if not logged in through discord?
    if request.method == 'POST':
        form = MemeSourceImageForm(request.discord_user, request.POST, request.FILES)
        if form.is_valid():
            form.save()
            DiscordSourceImgSubmission.objects.create(sourceimg=form.instance, discord_user=request.discord_user)
            return render(request, 'website/submit.html', {'success': True})
        else:
            print(form.errors)
            return render(request, 'website/submit.html', {'form': form, 'success': False})  # todo: show errors
    else:
        form = MemeSourceImageForm(request.discord_user)
    return render(request, 'website/submit.html', {'form': form})

website/templates/website/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'website/memeviewer.css' %}">
    {% endcompress %}
    <script
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>

    {% block head_extra %}{% endblock %}
    {% include 'website/favicons.html' %}

</head>
<body>

<h1><a href="{{ request.website_url }}">LambdaBot</a></h1>

{% block content %}{% endblock %}
<br>
{% if request.user.is_authenticated %}
    <p id="login_info">
        logged in as {{ request.discord_or_django_username }}
        {% if request.user.is_staff %}
            :: <a href="{% url 'admin:index' %}">admin</a>
        {% endif %}
        :: <a href="{% url 'discord_oauth2:logout' %}">log out</a>
    </p>
    <br>
{% endif %}
<div id="social">
    <a title="Source code" target="_blank" id="gh_icon" href="https://github.com/realyackson/lambdabot"></a>
    <a id="fb_icon" target="_blank" href="https://fb.com/lambdabot"></a>
    <a id="tw_icon" target="_blank" href="https://twitter.com/lambdabot3883"></a>
</div>
<br>
<p>© yackson 2018</p>

</body>
</html>

website/templates/website/favicons.html
{% load static %}

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'website/favicons/apple-touch-icon.png' %}?v=YAm878xwo9">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'website/favicons/favicon-32x32.png' %}?v=YAm878xwo9">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'website/favicons/favicon-16x16.png' %}?v=YAm878xwo9">
<link rel="manifest" href="{% static 'website/favicons/site.webmanifest' %}?v=YAm878xwo9">
<link rel="mask-icon" href="{% static 'website/favicons/safari-pinned-tab.svg' %}?v=YAm878xwo9" color="#f37c1b">
<link rel="shortcut icon" href="{% static 'website/favicons/favicon.ico' %}?v=YAm878xwo9">
<meta name="msapplication-TileColor" content="#f37c1b">
<meta name="msapplication-config" content="{% static 'website/favicons/browserconfig.xml' %}?v=YAm878xwo9">
<meta name="theme-color" content="#f37c1b">

website/templates/website/home.html
{% extends 'website/base.html' %}
{% load static %}

{% block head_extra %}

    <meta property="og:description" content="the meme bot"/>
    <meta property="og:title" content="LambdaBot"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="{{ request.website_url }}"/>
    <meta property="og:image" content="{% static 'website/img/gordon.png' %}"/>


    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@lambdabot3883">
    <meta name="twitter:creator" content="@lambdabot3883">
    <meta name="twitter:title" content="LambdaBot">

    <title>LambdaBot</title>

{% endblock %}

{% block content %}
    <h2>{{ discord_meme_count }}</h2>
    <h3>memes generated by</h3>
    <h2>{{ users_count }}</h2>
    <h3>users in</h3>
    <h2>{{ servers_count }}</h2>
    <h3>discord servers</h3>
    <div id="big_ass_button">
        <a target="_blank" id="add_to_discord" href="{% url 'website:bot_invite' %}">ADD TO DISCORD</a>
    </div>
    <br>

    <h2>{{ meme_count }}</h2>
    <h3>memes in total using</h3>
    <h2>{{ sourceimg_count }}</h2>
    <h3>source images and</h3>
    <h2>{{ template_count }}</h2>
    <h3>templates</h3>
    <div id="big_ass_button">
        <a id="submit_link" href="{% url 'website:submit' %}">SUBMIT IMAGE</a>
    </div>

{% endblock %}

website/templates/website/meme_info_view.html
{% extends 'website/base.html' %}
{% load static %}

{% block head_extra %}

    <meta property="og:title" content="LambdaBot meme #{{ meme.number }}"/>
    <meta property="og:type" content="article"/>
    <meta property="og:url" content="{{ meme.info_url }}"/>
    <meta property="og:image" content="{{ meme.url }}"/>
    <meta property="og:description" content="{{ meme.gen_date }}"/>

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@lambdabot3883">
    <meta name="twitter:creator" content="@lambdabot3883">
    <meta name="twitter:title" content="LambdaBot meme #{{ meme.number }}">
    <meta name="twitter:description" content="{{ meme.gen_date }}">
    <meta name="twitter:image" content="{{ meme.url }}">

    <title>LambdaBot meme #{{ meme.number }}</title>

{% endblock %}

{% block content %}

    <div class="memeinfo">
        <h3>#{{ meme.number }}</h3>
        <p id="date">
        {% if meme.facebookmeem %}
            <a href="https://facebook.com/{{  meme.facebookmeem.post }}" target="_blank">facebook :: {{ meme.facebookmeem.page.name }}</a>
        {% elif meme.twittermeem %}
            <a href="https://twitter.com/statuses/{{ meme.twittermeem.post }}" target="_blank">twitter :: {{ meme.twittermeem.page.name }} :: @{{ meme.twittermeem.page.handle }}</a>
        {% elif meme.discordmeem %}
            discord ::
            {% if meme.discordmeem.discord_channel.server %}
                {{ meme.discordmeem.discord_channel.server.name }} :: #{{ meme.discordmeem.discord_channel.name }}
            {% else %}
                DM
            {% endif %}
        {% endif %}
        </p>
        <p>{{ meme.gen_date }}</p>
        <a href="{{ meme.url }}">
            <img src="{{ meme.url }}" alt="meme"><br>
        </a>
        <br>
        {% if meme.template_link.bgimage_url %}
            <h4>template</h4>
            <a href="{{ meme.template_link.bgimage_url }}">
                <img src="{{ meme.template_link.bgimage_url }}" alt="template bg">
            </a>
        {% endif %}
        {% if meme.template_link.image_url %}
            <h4>template overlay</h4>
            <a href="{{ meme.template_link.image_url }}">
                <img src="{{ meme.template_link.image_url }}" alt="template fg">
            </a>
        {% endif %}
        <p>{{ meme.template_link }}</p>
        <br>
        <h4>source images</h4>
        {% for source_img in meme.sourceimgs %}
            <a href="{{ source_img.image_url }}">
                <img src="{{ source_img.image_url }}" alt="source image">
            </a><br>
        {% endfor %}
    </div>

{% endblock %}

website/templates/website/submission_queue.html
{% extends 'website/base.html' %}
{% load static %}

{% block head_extra %}

    <title>LambdaBot - submission queue</title>

{% endblock %}

{% block content %}



{% endblock %}

website/templates/website/submit.html
{% extends 'website/base.html' %}
{% load static %}

{% block head_extra %}
    <title>LambdaBot - submit image</title>
    <script>
        var no_img = "{% static 'website/img/image.png' %}";
    </script>
    <script src="{% static 'website/js/imageupload.js' %}"></script>
{% endblock %}

{% block content %}
    {% if success %}
        <h2>Nice 👍</h2>
        <p>Your image will be added once it's approved.</p>
        <div id="big_ass_button">
            <a id="submit_link" href="{% url 'website:submit' %}">ANOTHER ONE</a>
        </div>
    {% elif form.errors %}
        <h2>Oh no 😢</h2>
        {% if form.image_file.errors %}
            <p>{{ form.image_file.errors }}</p>
        {% elif form.captcha.errors %}
            <p>Captcha verification failed!</p>
        {% else %}
            <p>Something went wrong!</p>
        {% endif %}
        <div id="big_ass_button">
            <a id="submit_link" href="{% url 'website:submit' %}">TRY AGAIN</a>
        </div>
    {% else %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="memeinfo">
                <br>
                <h3 id="drop_file_info">choose / drop image below</h3>
                <div id="file_drop_wrapper">
                    <div id="file_drop_area">
                        <img id="submission_preview" src="{% static 'website/img/image.png' %}"><br>
                    </div>
                    {{ form.image_file }}
                </div>
                <div id="submission_info">
                    <p>{{ form.friendly_name }}</p>
                    <p title="image pool">{{ form.image_pool }}</p>
                    {{ form.captcha.errors }}
                    {{ form.captcha }}
                    <button type="submit">SUBMIT</button>
                    <p><a href="">cancel</a></p>
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}